apiVersion: v1
kind: Pod
metadata:
  name: welcome-pod
  labels:
    app: welcome
spec:
  containers:
  - name: welcome-container
    image: kicbase/echo-server:latest
    ports:
    - containerPort: 8080